// Generated by gencpp from file navigation_step/DestinationGoal.msg
// DO NOT EDIT!


#ifndef NAVIGATION_STEP_MESSAGE_DESTINATIONGOAL_H
#define NAVIGATION_STEP_MESSAGE_DESTINATIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace navigation_step
{
template <class ContainerAllocator>
struct DestinationGoal_
{
  typedef DestinationGoal_<ContainerAllocator> Type;

  DestinationGoal_()
    : POSE()
    , DURATION(0)  {
    }
  DestinationGoal_(const ContainerAllocator& _alloc)
    : POSE(_alloc)
    , DURATION(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _POSE_type;
  _POSE_type POSE;

   typedef uint32_t _DURATION_type;
  _DURATION_type DURATION;




  typedef boost::shared_ptr< ::navigation_step::DestinationGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_step::DestinationGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DestinationGoal_

typedef ::navigation_step::DestinationGoal_<std::allocator<void> > DestinationGoal;

typedef boost::shared_ptr< ::navigation_step::DestinationGoal > DestinationGoalPtr;
typedef boost::shared_ptr< ::navigation_step::DestinationGoal const> DestinationGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_step::DestinationGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_step::DestinationGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_step

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navigation_step': ['/home/ram/programming/ROS/catkin_ws/devel/share/navigation_step/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::DestinationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::DestinationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::DestinationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::DestinationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::DestinationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::DestinationGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_step::DestinationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9910fb1b8dd5ade93cdfabc520db130";
  }

  static const char* value(const ::navigation_step::DestinationGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9910fb1b8dd5adeULL;
  static const uint64_t static_value2 = 0x93cdfabc520db130ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_step::DestinationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_step/DestinationGoal";
  }

  static const char* value(const ::navigation_step::DestinationGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_step::DestinationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
geometry_msgs/Pose2D POSE\n\
uint32 DURATION\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::navigation_step::DestinationGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_step::DestinationGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.POSE);
      stream.next(m.DURATION);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DestinationGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_step::DestinationGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_step::DestinationGoal_<ContainerAllocator>& v)
  {
    s << indent << "POSE: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.POSE);
    s << indent << "DURATION: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.DURATION);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_STEP_MESSAGE_DESTINATIONGOAL_H
