// Generated by gencpp from file navigation_step/SetVelDirGoal.msg
// DO NOT EDIT!


#ifndef NAVIGATION_STEP_MESSAGE_SETVELDIRGOAL_H
#define NAVIGATION_STEP_MESSAGE_SETVELDIRGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace navigation_step
{
template <class ContainerAllocator>
struct SetVelDirGoal_
{
  typedef SetVelDirGoal_<ContainerAllocator> Type;

  SetVelDirGoal_()
    : TWIST()  {
    }
  SetVelDirGoal_(const ContainerAllocator& _alloc)
    : TWIST(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _TWIST_type;
  _TWIST_type TWIST;




  typedef boost::shared_ptr< ::navigation_step::SetVelDirGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_step::SetVelDirGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelDirGoal_

typedef ::navigation_step::SetVelDirGoal_<std::allocator<void> > SetVelDirGoal;

typedef boost::shared_ptr< ::navigation_step::SetVelDirGoal > SetVelDirGoalPtr;
typedef boost::shared_ptr< ::navigation_step::SetVelDirGoal const> SetVelDirGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_step::SetVelDirGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_step

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navigation_step': ['/home/ram/programming/ROS/catkin_ws/devel/share/navigation_step/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::SetVelDirGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::SetVelDirGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::SetVelDirGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbefa32ae2d63a70042886bd3c6d72be";
  }

  static const char* value(const ::navigation_step::SetVelDirGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbefa32ae2d63a70ULL;
  static const uint64_t static_value2 = 0x042886bd3c6d72beULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_step/SetVelDirGoal";
  }

  static const char* value(const ::navigation_step::SetVelDirGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
geometry_msgs/Twist TWIST\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::navigation_step::SetVelDirGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TWIST);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelDirGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_step::SetVelDirGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_step::SetVelDirGoal_<ContainerAllocator>& v)
  {
    s << indent << "TWIST: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.TWIST);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_STEP_MESSAGE_SETVELDIRGOAL_H
