// Generated by gencpp from file navigation_step/SetVelDirResult.msg
// DO NOT EDIT!


#ifndef NAVIGATION_STEP_MESSAGE_SETVELDIRRESULT_H
#define NAVIGATION_STEP_MESSAGE_SETVELDIRRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_step
{
template <class ContainerAllocator>
struct SetVelDirResult_
{
  typedef SetVelDirResult_<ContainerAllocator> Type;

  SetVelDirResult_()
    : RESULT(false)  {
    }
  SetVelDirResult_(const ContainerAllocator& _alloc)
    : RESULT(false)  {
  (void)_alloc;
    }



   typedef uint8_t _RESULT_type;
  _RESULT_type RESULT;




  typedef boost::shared_ptr< ::navigation_step::SetVelDirResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_step::SetVelDirResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelDirResult_

typedef ::navigation_step::SetVelDirResult_<std::allocator<void> > SetVelDirResult;

typedef boost::shared_ptr< ::navigation_step::SetVelDirResult > SetVelDirResultPtr;
typedef boost::shared_ptr< ::navigation_step::SetVelDirResult const> SetVelDirResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_step::SetVelDirResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_step::SetVelDirResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_step

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navigation_step': ['/home/ram/programming/ROS/catkin_ws/devel/share/navigation_step/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_step::SetVelDirResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_step::SetVelDirResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_step::SetVelDirResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "926778fb97d9ebdaf9d84fa1564c3bc0";
  }

  static const char* value(const ::navigation_step::SetVelDirResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x926778fb97d9ebdaULL;
  static const uint64_t static_value2 = 0xf9d84fa1564c3bc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_step/SetVelDirResult";
  }

  static const char* value(const ::navigation_step::SetVelDirResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool RESULT\n\
";
  }

  static const char* value(const ::navigation_step::SetVelDirResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.RESULT);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVelDirResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_step::SetVelDirResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_step::SetVelDirResult_<ContainerAllocator>& v)
  {
    s << indent << "RESULT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RESULT);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_STEP_MESSAGE_SETVELDIRRESULT_H
