TrajectoryPlannerROS:
    acc_lim_x: 2.0
    acc_lim_y: 2.0
    acc_lim_theta: 2.2
    max_vel_x: 1.8
    min_vel_x: 1.1
    max_rotational_vel: 1.5
    min_in_place_rotational_vel: 1.1
    escape_vel: -0.3
    holonomic_robot: true
    meter_scoring: true

    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2

    sim_time: 1.7
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 6

    goal_distance_bias: 0.8
    path_distance_bias: 0.6
    occdist_scale: 0.01
    heading_lookahead: 0.325
    dwa: false

    oscillation_reset_dist: 0.01
