#Independent settings for the planner's costmap
global_costmap:
    publish_voxel_map: false
    global_frame: /map
    robot_base_frame: /base_link
    update_frequency: 1
    publish_frequency: 0.5
    static_map: true
    rolling_window: false
    cost_scaling_factor: 5.0

    plugins:
        - {name: static_layer,      type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer,    type: "costmap_2d::VoxelLayer"}
        - {name: inflation_layer,   type: "costmap_2d::InflationLayer"} 
