#Independent settings for the local costmap
local_costmap:
    publish_voxel_map: false
    global_frame: /map
    robot_base_frame: /base_link
    update_frequency: 3.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.1
    origin_x: 0.0
    origin_y: 0.0

    plugins:
        - {name: static_layer,   type: "costmap_2d::StaticLayer"}
        - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
