#move_base global planner (navfn)
vfnROS: {
    #Creating plans that traverse unknown space is not allowed.
    allow_unknown: false
  }

footprint: [[0.26, 0.18],
             [0.31, 0.014],
             [0.31, -0.014],
             [0.26, -0.014],
             [0.26, -0.18],
             [-0.27, -0.18],
             [-0.27, 0.18]]

controller_frequency: 10.0
controller_patience: 5.0
clearing_radius: 0.25
footprint_padding: 0.03
recovery_behavior_enabled: false

#move_base local planner (base_local_planner)
TrajectoryPlannerROS: {
    #Robot Configuration Parameters
    acc_lim_x: 1.5,
    acc_lim_y: 1.5,
    acc_lim_theta: 2,
    max_vel_x: 1.8,
    #min_vel_x: 1.1,
    max_rotational_vel: 1.5,
    #min_in_place_rotational_vel: 1.1,
    escape_vel: -0.5,
    holonomic_robot: true,

    #Goal Tolerance Parameters
    xy_goal_tolerance: 0.1,
    yaw_goal_tolerance: 0.1,
    #If goal tolerance is latched, if the robot ever reaches the goal xy location 
    #it will simply rotate in place, even if it ends up outside the goal 
    #tolerance while it is doing so (1.3.1).
    latch_xy_goal_tolerance: true,

    #Forward Simulation Parameters
    sim_time: 1.4,
    sim_granularity: 0.05,
    vx_samples: 3,
    vtheta_samples: 6,
    #controller_frequency 20,

    #Trajectory Scoring Parameters
    meter_scoring: true,
    dwa: true,
    #Publish the cost grid that the planner will use when planning.
    publish_cost_grid_pc: true,
    global_frame_id: odom,
    pdist_scale: 0.6,
    gdist_scale: 0.8,
    occdist_scale: 0.02,
    heading_lookahead: 0.325,

    #Oscillation Prevention Parameters
    oscillation_reset_dist: 0.05

    #Global Plan Parameters
    # ---
  }

  #move_base local planner (base_local_planner)
  #TrajectoryPlannerROS: {
  #Robot Configuration Parameters
  



